### ISSUE TITLE
foldmethod=syntax by default

### ISSUE THREAD

**Issue by kopach** [pseewald/AnyFold#12]
Any chance to configure `foldmethod=syntax` instead of `foldmethod=expr` by default?
Tried with vim's `autocmd BufRead,BufNewFile * set foldmethod=syntax` but it's working randomly for me 😕

**Comment by pseewald** [comment]
If you have `let anyfold_activate=1` in your vimrc, foldmethod is always overridden by `foldmethod=expr` when vim-anyfold is initialised. This is because vim-anyfold relies on expression folding internally. If you want to use syntax folding for a specific file (for which vim-anyfold is active), you need to set foldmethod=syntax manually after opening the file. If you'd like to use vim-anyfold e.g. for Python but syntax folding for e.g. C++, I recommend to activate vim-anyfold for Python only:
```
autocmd Filetype python let b:anyfold_activate=1
autocmd Filetype cpp set foldmethod=syntax
```
