### ISSUE TITLE
re-fold

### ISSUE THREAD

**Issue by hk298** [pseewald/AnyFold#2]
The description on this site says `zx` can be used to re-fold everything. This command does nothing for me. However, `zM` does re-fold.

**Comment by pseewald** [comment]
`zx` resets folds (closes manually opened folds) but it opens the fold in which the cursor is placed. If you want to reset folds but not open cursor line, `zX` does the job. Note that `zx` and `zX` refold according to the currently set `foldlevel`, but `zM` sets `foldlevel` to `0` (closes all folds).

These commands are part of Vim and they are not changed in any way by this plugin. I simply mention `zx` in README.md because it is good to know if you work with folds.
