### ISSUE TITLE
What's the difference to foldmethod=indent

### ISSUE THREAD

**Issue by jounathaen** [pseewald/AnyFold#23]
Hi,
To be honest, I haven't installed the plugin, but just from reading the README, I don't get what the benefit of this plugin is, in contrast to vim's `foldmethod=indent`.
Would be nice to have this information in the README. :-)
Greets
Jounathaen

**Comment by pseewald** [comment]
Yes this should be documented! Why I started writing this plugin instead of using `foldmethod=indent`:
- `foldmethod=indent` only works for indents that are a multiple of `shiftwidth` and thus fails for aligned code lines and inconsistent indentation. Vim-anyfold correctly defines folds for arbitrary indents.
- Vim-anyfold recognizes braces as part of indented blocks and correctly folds them. I think it gives results comparable to filetype-specific folding plugins for e.g. C++ or Java.
- vim-anyfold optionally folds multiline comments.

A disadvantage of vim-anyfold is that it is much slower than `foldmethod=indent`. 

I will add this information to the README. Thank you!
