### ISSUE TITLE
AnyFold incorrectly detects foldable block boundaries in C files

### ISSUE THREAD

**Issue by AlexanderAmelkin** [pseewald/AnyFold#4]
At least in Linux kernel's scripts/kconfig/menu.c file I observe how wrongly the plugin detects the foldable blocks.

1. In expr_print() go to the closing curly brace of switch() and press spacebar. The text is folded up to the "default:" label above while it had to fold up to the beginning of switch()
2. In expr_print_gstr_helper() go to the function's closing brace and press spacebar. The text is folded up to "if (sym && sym->type != S_UNKNOWN)" while it should be folded up the the start of function definition.

Besides that, it would be nice to _not_ fold all foldable blocks automatically at file opening, but instead find and mark them as foldable so that the user could fold them when he wants by just pressing 'za' or whatever mapped key.

**Comment by pseewald** [comment]
Hi,
can you send me the file or a link where I can find the exact version of the file you are referring to? Right now, I can not find the locations in the file you mentioned. In general, foldable blocks are defined by indents and not by syntax, but I'm not sure if this helps with understanding the problem.

> Besides that, it would be nice to not fold all foldable blocks automatically at file opening, but instead find and mark them as foldable so that the user could fold them when he wants by just pressing 'za' or whatever mapped key.

You can set a higher foldlevel in your vimrc, e.g.
`set foldlevel=20`
does this work for you?

**Comment by pseewald** [comment]
I found the file, you mean scripts/kconfig/expr.c. I understand your points. Currently, AnyFold is based on indents only and it completely ignores braces. This is because I focused on languages without braces.

Indeed it would be very useful if AnyFold could detect blocks by braces such that braces have priority over indents. It's not difficult to generalize the current folding mechanism to braces and I'll give this a try.

**Comment by AlexanderAmelkin** [comment]
Thanks. Having the brace-based folding would be nice because the only language I can think of where block (and everything at all) is based on indents is Python. All other languages that I know use some kind of explicit block delimiters that sometimes can be omitted (for one-line blocks usually).

Maybe reuse syntax highlighting and/or autoindent somehow? I mean their mechanisms for detecting blocks.

**Comment by pseewald** [comment]
Since I have written this plugin with languages without braces in mind, I'm interested to hear how vim-anyfold could be useful for languages with braces. I could think of a few reasons:
- folding for languages that don't have built-in syntax folding support in vim?
- a folding method that is faster than syntax folding?
- a folding method that recognizes both braces and indent?
- other reasons?

Vim default syntax folding seems to work fine for C and now I'm not so sure anymore what gap vim-anyfold should fill for brace based languages.

Concerning reusing syntax highlighting: this can only be accessed via vim built-in `synID` (as far as I know), and for some reason this is very slow...
